### ISSUE TITLE
Vertaisarvionti

### ISSUE THREAD

**Issue by aleveste** [taisteluvalmis/Lets-chat#1]
Sovellusta oli helppoa käyttää ja se käyttäytyi tilannepäivityksen mukaisesti. Asioita mitä voisi muuttaa on miten saadaan admin-rooli, niin ettei kuka vaan voi saada sitä, ja redirectin lisääminen rekisteröitymisen jälkeen, esim login-sivulle.

**Comment by sandraole** [comment]
Kiitos vinkeistä!
